# .goreleaser.yaml
# GoReleaser configuration for Gistsync

version: 2

project_name: gistsync

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/karanshah229/gistsync/cmd.version={{.Version}} -X github.com/karanshah229/gistsync/cmd.Commit={{.Commit}} -X github.com/karanshah229/gistsync/cmd.Date={{.Date}}

archives:
  - formats: [tar.gz]
    # this name template makes the output archives look like:
    # gistsync_Darwin_arm64.tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 \"v1\") }}{{ .Amd64 }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
